### ISSUE TITLE
apt-get on every puppet run

### ISSUE THREAD

**Issue by Conzar** [Spantree/puppet-java8#5]
Java8 using the latest stdlib (2.2.2), every puppet run produces the following:

```
Notice: /Stage[main]/Java8/Apt::Ppa[ppa:webupd8team/java]/Exec[add-apt-repository-ppa:webupd8team/java]/returns: executed successfully
Info: /Stage[main]/Java8/Apt::Ppa[ppa:webupd8team/java]/Exec[add-apt-repository-ppa:webupd8team/java]: Scheduling refresh of Class[Apt::Update]
Notice: /Stage[main]/Java8/Exec[apt-update]/returns: executed successfully
```

**Comment by divideby0** [comment]
Hi @Conzar thanks for the feedback on this. Would you be up for submitting a pull request with a fix?

**Comment by Conzar** [comment]
I can look into it to find out what the problem might be.

**Comment by Conzar** [comment]
Note, I made a PR which passes all tests here: https://github.com/Spantree/puppet-java8/pull/6

**Comment by feniix** [comment]
Merged
